from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol


class ConversationStore(Protocol):
    async def list_conversations(self) -> List[Dict[str, Any]]: ...
    async def create_conversation(self, conversation_id: str) -> Dict[str, Any]: ...
    async def get_conversation(self, conversation_id: str) -> Optional[Dict[str, Any]]: ...
    async def add_user_message(self, conversation_id: str, content: str) -> None: ...
    async def add_assistant_message(
        self,
        conversation_id: str,
        stage1: List[Dict[str, Any]],
        stage2: List[Dict[str, Any]],
        stage3: Dict[str, Any],
    ) -> None: ...
    async def update_conversation_title(self, conversation_id: str, title: str) -> None: ...
